# Generated by Django 4.1.1 on 2023-05-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهرستان', 'verbose_name_plural': 'شهرستان\u200cها'},
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.city', verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.IntegerField(choices=[(1, 'محله'), (2, 'روستا')], verbose_name='نوع'),
        ),
    ]
