# Generated by Django 4.1.1 on 2024-08-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_options_residenceplace_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'محله/روستا', 'verbose_name_plural': 'محله\u200cها/روستاها'},
        ),
        migrations.AlterField(
            model_name='residenceplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.place', verbose_name='محله/روستا'),
        ),
    ]
