# Generated by Django 4.1.1 on 2023-05-28 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import users.managers
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShnUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile', models.CharField(error_messages={'unique': 'کاربری با این شماره موبایل موجود است.'}, max_length=11, unique=True, validators=[users.validators.MobileNumberValidator()], verbose_name='شماره موبایل')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('image', models.ImageField(default='user.png', upload_to='', verbose_name='عکس پروفایل')),
                ('is_submitter', models.BooleanField(default=False, help_text='مشخص می\u200cکند که آیا کاربر می\u200cتواند شخص جدید به شجره\u200cنامه اضافه کند یا خیر.', verbose_name='کاربر ثبت کننده شجره\u200cنامه')),
                ('is_approver', models.BooleanField(default=False, help_text='مشخص می\u200cکند که کاربر می\u200cتواند شخص جدید و تایید شده به شجره\u200cنامه اضافه کند و یا اشخاص اضافه شده به شجره\u200cنامه توسط کاربران ثبت\u200cکننده را تایید کند یا خیر.', verbose_name='کاربر تایید کننده شجره\u200cنامه')),
                ('is_staff', models.BooleanField(default=False, help_text='مشخص می\u200cکند که آیا کاربر می\u200cتواند وارد پنل مدیریت شود یا خیر.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='مشخص میکند که آیا کاربر به عنوان فعال در نظر گرفته می\u200cشود یا خیر.به جای حذف کاربر این فیلد غیرفعال می\u200cشود.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', users.managers.ShnUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AuthOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(choices=[('RG', 'ثبت\u200cنام'), ('RP', 'فراموشی رمز\u200cعبور')], max_length=2, verbose_name='کاربرد')),
                ('code', models.CharField(max_length=5, verbose_name='رمز یک\u200cبارمصرف')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رمز یک\u200cبارمصرف',
                'verbose_name_plural': 'رمز\u200cهای یک\u200cبارمصرف',
                'ordering': ('created_at',),
            },
        ),
    ]
