# Generated by Django 4.1.1 on 2023-04-13 06:46

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authotp',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='shnuser',
            name='mobile',
            field=models.CharField(error_messages={'unique': 'کاربری با این نام کاربری وجود دارد'}, max_length=11, unique=True, validators=[users.validators.MobileNumberValidator()], verbose_name='شماره موبایل'),
        ),
    ]
