# Generated by Django 4.1.1 on 2023-06-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shnuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shnuser',
            name='last_name',
        ),
    ]
