# Generated by Django 4.1.1 on 2023-06-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shnuser',
            name='national_code',
        ),
    ]
