# Generated by Django 4.1.1 on 2023-04-14 11:52

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authotp_confirmed_alter_shnuser_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authotp',
            name='usage',
            field=models.CharField(choices=[('RG', 'ثبت\u200cنام'), ('LG', 'ورود'), ('RP', 'فراموشی رمز\u200cعبور')], default='RG', max_length=2, verbose_name='کاربرد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shnuser',
            name='mobile',
            field=models.CharField(error_messages={'unique': 'کاربری با این شماره موبایل موجود است.'}, max_length=11, unique=True, validators=[users.validators.MobileNumberValidator()], verbose_name='شماره موبایل'),
        ),
    ]
