# Generated by Django 4.1.1 on 2024-05-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_shnuser_national_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authotp',
            options={'ordering': ('-created_at',), 'verbose_name': 'رمز یک\u200cبارمصرف', 'verbose_name_plural': 'رمز\u200cهای یک\u200cبارمصرف'},
        ),
    ]
