upstream django_asgi {
  server  django_asgi:8000;
}

server {
    listen 80           default_server;
    root                /usr/src/app;
    client_max_body_size 60M;

    location / {
      proxy_pass http://django_asgi;

      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_redirect off;
    }

    location /static {
        alias /static;
    }

    location /media {
        alias /media;
    }
}