# Generated by Django 4.1.1 on 2024-06-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authotp_updated_at_alter_authotp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shnuser',
            name='is_approver',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند که کاربر می\u200cتواند شخص جدید و تایید شده به درخت\u200cخانوادگی اضافه کند و یا اشخاص اضافه شده به درخت\u200cخانوادگی توسط کاربران ثبت\u200cکننده را تایید کند یا خیر.', verbose_name='کاربر تایید کننده درخت\u200cخانوادگی'),
        ),
        migrations.AlterField(
            model_name='shnuser',
            name='is_submitter',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند که آیا کاربر می\u200cتواند شخص جدید به درخت\u200cخانوادگی اضافه کند یا خیر.', verbose_name='کاربر ثبت کننده درخت\u200cخانوادگی'),
        ),
    ]
