# Generated by Django 4.1.1 on 2025-06-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_shnuser_is_approver_alter_shnuser_is_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shnuser',
            name='is_approver',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند که کاربر می\u200cتواند شخص جدید و تایید شده به شجره\u200cنامه اضافه کند و یا اشخاص اضافه شده به شجره\u200cنامه توسط کاربران ثبت\u200cکننده را تایید کند یا خیر.', verbose_name='کاربر تایید کننده شجره\u200cنامه'),
        ),
        migrations.AlterField(
            model_name='shnuser',
            name='is_submitter',
            field=models.BooleanField(default=False, help_text='مشخص می\u200cکند که آیا کاربر می\u200cتواند شخص جدید به شجره\u200cنامه اضافه کند یا خیر.', verbose_name='کاربر ثبت کننده شجره\u200cنامه'),
        ),
    ]
