# Generated by Django 4.1.1 on 2025-06-06 15:45

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_shnuser_is_approver_alter_shnuser_is_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shnuser',
            name='mobile',
            field=models.CharField(error_messages={'unique': 'کاربری با این شماره موبایل موجود است. لطفا از طریق "فراموشی رمز عبور" اقدام به تعیین رمز عبور کنید.'}, max_length=11, unique=True, validators=[users.validators.MobileNumberValidator()], verbose_name='شماره موبایل'),
        ),
    ]
