# Generated by Django 4.1.1 on 2023-02-17 17:58

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='اسم')),
                ('last_name', models.CharField(max_length=150, verbose_name='فامیلی')),
                ('gender', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], verbose_name='جنسیت')),
                ('birth_year', models.SmallIntegerField(verbose_name='سال تولد')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('death_year', models.SmallIntegerField(blank=True, null=True, verbose_name='سال وفات')),
                ('death_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ وفات')),
                ('birth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.place', verbose_name='محل تولد')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='father_children', to='persons.person', verbose_name='پدر')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mother_children', to='persons.person', verbose_name='مادر')),
                ('residence_place', models.ManyToManyField(blank=True, to='places.residenceplace', verbose_name='محل سکونت')),
                ('spouse', models.ManyToManyField(blank=True, to='persons.person', verbose_name='همسر')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
            },
        ),
    ]
