# Generated by Django 4.1.1 on 2024-06-21 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0002_alter_city_options_alter_place_city_alter_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='اسم')),
                ('last_name', models.CharField(max_length=150, verbose_name='فامیلی')),
                ('gender', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], verbose_name='جنسیت')),
                ('birth_year', models.SmallIntegerField(verbose_name='سال تولد')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('death_year', models.SmallIntegerField(blank=True, null=True, verbose_name='سال وفات')),
                ('death_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ وفات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش')),
                ('matching_status', models.IntegerField(choices=[(0, 'بدون انطباق'), (1, 'در حال تطابق'), (2, 'تطابق یافته')], default=0, verbose_name='وضعیت تطابق')),
                ('birth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.place', verbose_name='محل تولد')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_persons', related_query_name='created_person', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='father_children', to='persons.person', verbose_name='پدر')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_children', to='persons.person', verbose_name='مادر')),
                ('residence_place', models.ManyToManyField(blank=True, to='places.residenceplace', verbose_name='محل سکونت')),
                ('spouses', models.ManyToManyField(blank=True, to='persons.person', verbose_name='همسر')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
            },
        ),
        migrations.CreateModel(
            name='RelationMatchingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('FATHER', 'پدر'), ('MOTHER', 'مادر'), ('SPOUSE', 'همسر'), ('CHILD', 'فرزند')], max_length=10, verbose_name='نسبت')),
                ('status', models.IntegerField(choices=[(0, 'در انتظار تعیین مشابه'), (1, 'مشابه تعیین شده\u200cاست'), (2, 'در انتظار تایید تطابق'), (3, 'تطابق انجام شده\u200cاست'), (4, 'تشابه رد شد')], default=0, verbose_name='وضعیت')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_requests', related_query_name='relation_request', to='persons.person', verbose_name='شخص')),
                ('related_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relation_request_related', to='persons.person', verbose_name='شخص وابسته')),
                ('similar_related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_request_similar_related', to='persons.person', verbose_name='شخص وابسته مشابه')),
            ],
            options={
                'verbose_name': 'درخواست تطابق وابستگان',
                'verbose_name_plural': 'درخواست\u200cهای تطابق وابستگان',
            },
        ),
    ]
