# Generated by Django 4.1.1 on 2024-06-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='matching_status',
            field=models.IntegerField(choices=[(0, 'بدون انطباق'), (1, 'در حال تطابق'), (2, 'تطابق یافته')], default=0, verbose_name='وضعیت تطابق'),
        ),
        migrations.CreateModel(
            name='RelationMatchingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'در انتظار تعیین مشابه'), (1, 'مشابه تعیین شده\u200cاست'), (2, 'در انتظار تایید تطابق'), (3, 'تطابق انجام شده\u200cاست'), (4, 'تشابه رد شد')], default=0, verbose_name='وضعیت')),
                ('relation', models.CharField(choices=[('FATHER', 'پدر'), ('MOTHER', 'مادر'), ('SPOUSE', 'همسر'), ('CHILD', 'فرزند')], max_length=10, verbose_name='نسبت')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_requests', related_query_name='relation_request', to='persons.person', verbose_name='شخص')),
                ('related_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relation_request_related', to='persons.person', verbose_name='شخص وابسته')),
                ('similar_related_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_request_similar_related', to='persons.person', verbose_name='شخص وابسته مشابه')),
            ],
            options={
                'verbose_name': 'درخواست تطابق وابستگان',
                'verbose_name_plural': 'درخواست\u200cهای تطابق وابستگان',
            },
        ),
    ]
