# Generated by Django 4.1.1 on 2024-08-23 12:23

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_remove_person_residence_place_alter_person_father_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationmatchingrequest',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationmatchingrequest',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان آخرین ویرایش'),
        ),
    ]
