# Generated by Django 4.1.1 on 2024-07-18 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0002_person_can_see_tree_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeeTreePermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'در انتظار تایید'), (2, 'تایید شده')], default=1, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر متقاضی')),
                ('person', models.ForeignKey(help_text='شخصی که کاربر میخواهد دسترسی مشاهده درخت\u200cخانوادگی او را داشته باشد.', on_delete=django.db.models.deletion.CASCADE, to='persons.person', verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'درخواست دریافت دسترسی مشاهده درخت\u200cخانوادگی',
                'verbose_name_plural': 'درخواست\u200cهای دریافت دسترسی مشاهده درخت\u200cخانوادگی',
            },
        ),
    ]
