# Generated by Django 4.1.1 on 2024-08-23 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0003_relationmatchingrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationmatchingrequest',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_relation_matching_requests', related_query_name='created_relation_matching_request', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
            preserve_default=False,
        ),
    ]
