# Generated by Django 4.1.1 on 2025-02-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_relationmatchingrequest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='seetreepermissionrequest',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='relationmatchingrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار تعیین مشابه'), (2, 'در انتظار تایید تطابق'), (3, 'تطابق انجام شده'), (4, 'تطابق رد شده')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='seetreepermissionrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'در انتظار تایید'), (2, 'تایید شده'), (3, 'رد شده')], default=1, verbose_name='وضعیت'),
        ),
    ]
