# Generated by Django 4.1.1 on 2025-02-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_seetreepermissionrequest_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seetreepermissionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست دریافت دسترسی مشاهده درخت\u200cخانوادگی', 'verbose_name_plural': 'درخواست\u200cهای دریافت دسترسی مشاهده درخت\u200cخانوادگی'},
        ),
    ]
