# Generated by Django 4.1.1 on 2025-06-06 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0006_alter_seetreepermissionrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seetreepermissionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست دریافت دسترسی مشاهده شجره\u200cنامه', 'verbose_name_plural': 'درخواست\u200cهای دریافت دسترسی مشاهده شجره\u200cنامه'},
        ),
        migrations.AlterField(
            model_name='person',
            name='can_see_tree_users',
            field=models.ManyToManyField(related_name='can_see_persons_tree', to=settings.AUTH_USER_MODEL, verbose_name='کاربرانی که می\u200cتوانند شجره\u200cنامه این شخص را ببینند.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seetreepermissionrequest',
            name='person',
            field=models.ForeignKey(help_text='شخصی که کاربر میخواهد دسترسی مشاهده شجره\u200cنامه او را داشته باشد.', on_delete=django.db.models.deletion.CASCADE, to='persons.person', verbose_name='شخص'),
        ),
    ]
