# Generated by Django 4.1.1 on 2025-06-14 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0007_alter_seetreepermissionrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_persons', related_query_name='created_person', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط'),
        ),
    ]
