# Generated by Django 4.1.1 on 2025-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_alter_person_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم مستعار'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='سال تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='فامیلی'),
        ),
    ]
