# Generated by Django 4.1.1 on 2023-02-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'شهرستان'), (2, 'روستا')], verbose_name='نوع')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ResidencePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.SmallIntegerField(verbose_name='از سال')),
                ('to_year', models.SmallIntegerField(verbose_name='تا سال')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.place', verbose_name='مکان')),
            ],
            options={
                'verbose_name': 'محل سکونت',
                'verbose_name_plural': 'محل\u200cهای سکونت',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.province', verbose_name='استان'),
        ),
    ]
