# Generated by Django 4.1.1 on 2024-08-07 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_remove_person_residence_place_alter_person_father_and_more'),
        ('places', '0002_alter_city_options_alter_place_city_alter_place_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'محله', 'verbose_name_plural': 'محله\u200cها'},
        ),
        migrations.AddField(
            model_name='residenceplace',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='persons.person', verbose_name='شخص'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residenceplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.place', verbose_name='محله'),
        ),
    ]
