# Generated by Django 4.1.1 on 2023-02-17 17:58

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی تیکت',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای تیکت',
            },
        ),
        migrations.CreateModel(
            name='AnonymousTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(verbose_name='شرح تیکت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('answer', models.TextField(verbose_name='پاسخ تیکت')),
                ('answered_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان پاسخ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.ticketcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
                'ordering': ('created_at',),
            },
        ),
    ]
